# workflow for unit test

name: Test
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags-ignore:
      - 'v*' # don't run on version tags
    branches:
      - '**'

jobs:
  test:
   name: test
   runs-on: ubuntu-latest
   steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        go get -v -t -d .
        
    - name: Test
      run: go test ./...

        
